### ISSUE TITLE
It seems Faro web SDK has broken mux player manifest downloads on Chrome.

### ISSUE THREAD

**Issue by discardedhunk** [grafana/faro-web-sdk#691]
## Description

Faro web SDK has broken mux player manifest downloads on Chrome.
Suddenly, at 3 a.m. on September 26, we started seeing errors from our users unable to play videos on our platform. We reached out to Mux, and they suggested removing the faro-web-sdk. Once we did, the problem was resolved.

## Steps to reproduce

Install faro-web-sdk and faro-web-tracing in javascript, along with mux-player 3.0. Trying playing a video with these installed and you should see an error in the chrome console that mux is not able to download the manifest file.
Here's a snippet from the error:
text: "t.match is not a function" (this is the error from the manifest download)
url: "https://manifest-gcp-us-east1-vop1.cfcdn.mux.com/Hz3Sqwrwts00wd6CUAW02AKKoqlg6h6cNg4YaOrR9oM01YmjV01rJKqmnqFRI02MIO1i4Kd88QXxZ4Z7EgoSpZDG13LzuaD5M4Ulj/rendition.m3u8?cdn=fastly&expires=1727985600&skid=default&signature=NjZmZWY3YzBfYTUyNDUzNTAyNDIwYzllMzk2YmM2ODUwN2ExNWFkNDAyYWEzZWRkNWFkMTllNjhiYzY5MTQ4MGIwZDhkNGExMw==&vsid=TX2DtxjimI4r1MUlLNLKSQigRpwTSW3oNw7ZJZnkWDfK01D6bI8TBLMXhxBFGwlAyn0

## Expected behavior

faro-web-SDK and web-tracing work with mux-player 3.0, on Chrome, without error. This worked in Safari. 

## Actual behavior

Errors from mux downloading manifest file

## Environment

- **SDK version:**
- https://unpkg.com/@grafana/faro-web-sdk@^1.9.0/dist/bundle/faro-web-sdk.iife.js"
- **SDK instrumentations:**
- https://unpkg.com/@grafana/faro-web-tracing@^1.9.0/dist/bundle/faro-web-tracing.iife.js"
- **Device type:**
- **Device name:**
- **OS:** MacOS, Windows
- **Browser:**
- Google Chrome

**Comment by codecapitano** [comment]
Hi @discardedhunk 

I can reproduce the issue.
Seems that the `web-tracing` package causes the problem.

Now investigating why it causes the problem.

**Comment by codecapitano** [comment]
Hi @discardedhunk we [fixed the issue](https://github.com/grafana/faro-web-sdk/pull/695) and will release a new Faro version today.
Thanks again for reporting.

**Comment by discardedhunk** [comment]
Great! Thank you so much

**Comment by codecapitano** [comment]
@discardedhunk Does Faro 1.10.2solve your issue?

**Comment by discardedhunk** [comment]
@codecapitano yes, thank you.
